### ISSUE TITLE
Deleted idea still shows in list

### ISSUE THREAD

**Issue by Derky** [phpbb/ideas#58]
VSE's test idea is still showing in the list while it was deleted

**Comment by VSEphpbb** [comment]
That's a dot-com related issue only.

**Comment by DavidIQ** [comment]
What needs to be done on .com for deleting to work?

**Comment by VSEphpbb** [comment]
I don't know, but @michaelcullum had us create that field to input a specific URL in order to bypass the normally generated URL for .com.

On a normal forum installation, the extension deletes ideas just fine.

By the way, the test idea should probably be tried out again, as @DavidIQ was playing with all the settings while I was testing things out, so something could have gone wrong at the time too.

**Comment by VSEphpbb** [comment]
These lines are defaults and could be removed:
https://github.com/phpbb/phpbb/blob/master/phpBB/includes/functions.php#L2109

Also should throw an error message when non-mod tries to delete
