### ISSUE TITLE
Feature - Repalce RFC by Pull Request link

### ISSUE THREAD

**Issue by Nicofuma** [phpbb/ideas#74]
RFC are gone but it could be nice to provide the PR links if it exists

**Comment by DavidIQ** [comment]
Not sure if we really need to do this since the pr link would be in the ticket. So maybe we just get rid of this field altogether?

**Comment by VSEphpbb** [comment]
I agree with @DavidIQ as the RFC link was from a time when there separate RFC's required for all new development tasks. Linking to just the ticket (which also may contain any and all related PRs) is more streamlined and gives the Moderators less work to do in hunting down links - now they just need to supply the ticket link and done!

**Comment by rxu** [comment]
As per the <a href="http://area51.phpbb.com/phpBB/viewtopic.php?f=99&t=52121">Changes to use of tracker, ideas, and reporting process</a> announcement, "all new feature or improvement tickets will be closed, if there isn't a pull request belonging to that ticket".
Thus, having just a ticket link can be just useless. It seems that it would be wise to have an option to select what to link to (RFC/ticket/PR), or even to be able to link to anything.

**Comment by VSEphpbb** [comment]
@rxu RFCs are gone. And there will always be a ticket, so the ticket link works (as mentioned you can find the PR in the ticket). PR's come and go, some get closed and reopned as new Pos, so they're too volatile to use. But the ticket, in theory is the most stable link to have. Plus the ticket provides more information than a PR does.

**Comment by VSEphpbb** [comment]
Oh that's a new policy I see in that link there... :/

**Comment by VSEphpbb** [comment]
Based on this:
> Only open bug tickets in the tracker unless you are working on a feature or improvement (you will shortly open a pull request). All new feature or improvement tickets will be closed, if there isn't a pull request belonging to that ticket.

The ticket tracker is only for bugs and new features/improvements. Since Ideas is for new/improvements, it should still link to the ticket tracker, and according to that policy, every new improvement in the tracker must have a PR linked to it. So I think I still agree with @DavidIQ and we just lose the RFC field and stick with tickets only.

**Comment by rxu** [comment]
@VSEphpbb 

>Only open bug tickets in the tracker unless you are working on a feature or improvement (you will shortly open a pull request).

So you can get a lot of cases of having just RFCs, as imho very low part of people who suggest features/improvements are actually working on their implementations. Mostly often we have only bare ideas which suggesters want development to implement, nothing more. imho.

**Comment by rxu** [comment]
> RFC are gone

The main issue is they aren't 😛

**Comment by VSEphpbb** [comment]
We don't care about RFC's anymore as far as Ideas is concerned. The Idea is the RFC for new features now. ANy RFC on area51 is just for technical help by the coder of the feature, and will most likely not be used much since PRs are where the bulk of coding/helping occurs now. RFC's are not to be started as part of any normal new feature/improvement process. So in fact there should be little to no RFCs anymore.

True the Idea will start as a suggestion. But discussion is encouraged in the Idea (not on Area51) to work out the details of the idea, and even to discuss technical assistance for anyone who might want to start it if a regular dev does not start it.

The problem we want to mitigate is "sprawl". We need to localise things. having a single external link for the ideas development, ie: the ticket, is the best option as the ticket will itself lead to any related PR's and even Area51 topics if they exist. But having a variety of links and destinations spreading out from an Ideas topics can just get people lost...whether they land on the tracker, or area51 or github. It'll spin some users heads too much ;)

**Comment by rxu** [comment]
Although, I don't personally understand why do we need RFCon Area51 to discuss new features/improwements while we have ideas tracking for that now.

**Comment by VSEphpbb** [comment]
We don't discuss new features or improvements on area51 anymore.

**Comment by rxu** [comment]
So adjust the policy linked above? 😉

**Comment by VSEphpbb** [comment]
@rxu the policy is correct:

If you would like to **discuss technical details** about a new feature or improvement to the core with the team or the community, feel free to open an RFC in the Area51 forums.

**Comment by VSEphpbb** [comment]
I think rather than eliminating it, we keep the RFC links that are already there from old ideas. We just stop allowing new RFC links from being added for any ideas that don't already have one. @DavidIQ @Nicofuma ?

**Comment by DavidIQ** [comment]
So you mean remove the feature to add the link and just leave and display the ones that are already present? I'm fine with that.

**Comment by VSEphpbb** [comment]
No. Not to add anything. Just remove adding new RFC links. Leave old one’s in place (and the ability to still edit them).

**Comment by VSEphpbb** [comment]
I misread what you said. Yes, I think we’re saying the same thing :S

**Comment by DavidIQ** [comment]
We are 😜
